version: '3.8'

services:
  db_mps:
    image: mysql:8.0.30-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mps_viveo
    ports:
      - "3307:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
